<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel ="stylesheet" href="/css/style.css">
</head>

<body>

    <div>
        <a href="index.html">
            <h1>Animal Gallery</h1>
        </a>
    </div>

    <nav class="navbar">
        <a href="index.html">Home</a>
        <a href="about.html">About</a>
        <a href="new-animal-form.html">Add Animal</a>
    </nav>

<div>
    <h2>${hawk.name}</h2>
</div>

<div class="hawksdetails">
    <img src="/Images/Red Tailed Hawk.webp" alt="Red-Tailed Hawk">
    <img src="/Images/Red Tailed Hawk 2.png" alt="Red-Tailed Hawk">        <img src="/Images/Red Tailed Hawk 3.jpg" alt="Red-Tailed Hawk">
    <div class="desc"> Red-Tailed Hawks are one of the most common and widepread birds of
        prey in North America. They are recognized by their broad wings, reddish-brown tail, and 
        peircing call, which movies often portray as coming from an American Bald Eagle. Being highly
        adaptable, they thrive in diverse habitats ranging from deserts and grasslands to urban areas.
    </div>
</div>

</body>

</html>